name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_windows:
    name: Windows Client
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: inter_knot_windows_x64
          path: build/windows/x64/runner/Release

  build_android:
    name: Android Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: inter_knot_apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: inter_knot_appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  build_iOS:
    name: iOS Client
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter build ios --release --no-codesign
      - run: flutter build ipa --release --no-codesign
      - run: ls -R

  build_macOS:
    name: macOS Client
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter build macos
      - run: ls -R

  build_linux:
    name: Linux Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux
      - run: ls -R

  build_web:
    name: Web Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter build web --base-href /inter_knot/ --web-renderer html
      - uses: actions/upload-artifact@v3
        with:
          name: inter_knot_web
          path: build/web
